# -*- coding: utf-8 -*-
"""Cartoon Image Generator with OpenCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qarUGlUzDI03S0E7zLkHF9sEeY0ONLoi

##Import required libraries
"""

import cv2  # for image processing
import easygui  # to open the filebox
import numpy as np  # to store image
import imageio  # to read image stored at particular path
import sys
import matplotlib.pyplot as plt
import os
import tkinter as tk
from tkinter import filedialog
from tkinter import *
from PIL import ImageTk, Image

"""##Upload the Original Image"""

def upload(ImagePath):
  cartoonify(ImagePath)

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Resize the image
    ReSized1 = cv2.resize(originalImage, (960, 540))
    plt.imshow(ReSized1)
    plt.title("Original Image")
    plt.axis("off")
    plt.show()

upload('/content/AA.jpg')

"""##Convert image to grayscale"""

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Convert image to grayscale
    grayScaleImage = cv2.cvtColor(originalImage, cv2.COLOR_RGB2GRAY)
    ReSized2 = cv2.resize(grayScaleImage, (960, 540))
    plt.imshow(ReSized2, cmap='gray')
    plt.title("Grayscale Image")
    plt.axis("off")
    plt.show()

upload('/content/AA.jpg')

"""###Applying median blur to smoothen an image"""

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Convert image to grayscale
    grayScaleImage = cv2.cvtColor(originalImage, cv2.COLOR_RGB2GRAY)
    ReSized2 = cv2.resize(grayScaleImage, (960, 540))

    # Applying median blur to smoothen an image
    smoothGrayScale = cv2.medianBlur(grayScaleImage, 5)
    ReSized3 = cv2.resize(smoothGrayScale, (960, 540))
    plt.imshow(ReSized3, cmap='gray')
    plt.title("Smoothened Grayscale Image")
    plt.axis("off")
    plt.show()

upload('/content/AA.jpg')

"""##Retrieving edges using adaptive thresholding"""

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Resize the image
    ReSized1 = cv2.resize(originalImage, (960, 540))

    # Convert image to grayscale
    grayScaleImage = cv2.cvtColor(originalImage, cv2.COLOR_RGB2GRAY)
    ReSized2 = cv2.resize(grayScaleImage, (960, 540))

    # Applying median blur to smoothen an image
    smoothGrayScale = cv2.medianBlur(grayScaleImage, 5)
    ReSized3 = cv2.resize(smoothGrayScale, (960, 540))


    # Retrieving edges for cartoon effect using adaptive thresholding
    getEdge = cv2.adaptiveThreshold(smoothGrayScale, 255,
                                    cv2.ADAPTIVE_THRESH_MEAN_C,
                                    cv2.THRESH_BINARY, 9, 9)
    ReSized4 = cv2.resize(getEdge, (960, 540))
    plt.imshow(ReSized4, cmap='gray')
    plt.title("Edges")
    plt.axis("off")
    plt.show()
upload('/content/AA.jpg')

"""##Applying bilateral filter to remove noise"""

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Resize the image
    ReSized1 = cv2.resize(originalImage, (960, 540))

    # Convert image to grayscale
    grayScaleImage = cv2.cvtColor(originalImage, cv2.COLOR_RGB2GRAY)
    ReSized2 = cv2.resize(grayScaleImage, (960, 540))

    # Applying median blur to smoothen an image
    smoothGrayScale = cv2.medianBlur(grayScaleImage, 5)
    ReSized3 = cv2.resize(smoothGrayScale, (960, 540))


    # Retrieving edges for cartoon effect using adaptive thresholding
    getEdge = cv2.adaptiveThreshold(smoothGrayScale, 255,
                                    cv2.ADAPTIVE_THRESH_MEAN_C,
                                    cv2.THRESH_BINARY, 9, 9)
    ReSized4 = cv2.resize(getEdge, (960, 540))

    # Applying bilateral filter to remove noise and keep edges sharp
    colorImage = cv2.bilateralFilter(originalImage, 9, 300, 300)
    ReSized5 = cv2.resize(colorImage, (960, 540))
    plt.imshow(ReSized5, cmap='gray')
    plt.title("Bilateral Filter")
    plt.axis("off")
    plt.show()

upload('/content/AA.jpg')

"""##Masking edged image with our filtered color image"""

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Resize the image
    ReSized1 = cv2.resize(originalImage, (960, 540))

    # Convert image to grayscale
    grayScaleImage = cv2.cvtColor(originalImage, cv2.COLOR_RGB2GRAY)
    ReSized2 = cv2.resize(grayScaleImage, (960, 540))

    # Applying median blur to smoothen an image
    smoothGrayScale = cv2.medianBlur(grayScaleImage, 5)
    ReSized3 = cv2.resize(smoothGrayScale, (960, 540))


    # Retrieving edges for cartoon effect using adaptive thresholding
    getEdge = cv2.adaptiveThreshold(smoothGrayScale, 255,
                                    cv2.ADAPTIVE_THRESH_MEAN_C,
                                    cv2.THRESH_BINARY, 9, 9)
    ReSized4 = cv2.resize(getEdge, (960, 540))

    # Applying bilateral filter to remove noise and keep edges sharp
    colorImage = cv2.bilateralFilter(originalImage, 9, 300, 300)
    ReSized5 = cv2.resize(colorImage, (960, 540))

    # Masking edged image with our filtered color image
    cartoonImage = cv2.bitwise_and(colorImage, colorImage, mask=getEdge)
    ReSized6 = cv2.resize(cartoonImage, (960, 540))
    plt.imshow(ReSized6, cmap='gray')
    plt.title("Cartoon")
    plt.axis("off")
    plt.show()

upload('/content/AA.jpg')

"""##Plotting the whole transition & Save it"""

def cartoonify(ImagePath):
    # Read the image
    originalImage = cv2.imread(ImagePath)
    originalImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2RGB)

    # Confirm that image is chosen
    if originalImage is None:
        print("Cannot find any image. Choose an appropriate file.")
        sys.exit()

    # Resize the image
    ReSized1 = cv2.resize(originalImage, (960, 540))

    # Convert image to grayscale
    grayScaleImage = cv2.cvtColor(originalImage, cv2.COLOR_RGB2GRAY)
    ReSized2 = cv2.resize(grayScaleImage, (960, 540))

    # Applying median blur to smoothen an image
    smoothGrayScale = cv2.medianBlur(grayScaleImage, 5)
    ReSized3 = cv2.resize(smoothGrayScale, (960, 540))


    # Retrieving edges for cartoon effect using adaptive thresholding
    getEdge = cv2.adaptiveThreshold(smoothGrayScale, 255,
                                    cv2.ADAPTIVE_THRESH_MEAN_C,
                                    cv2.THRESH_BINARY, 9, 9)
    ReSized4 = cv2.resize(getEdge, (960, 540))

    # Applying bilateral filter to remove noise and keep edges sharp
    colorImage = cv2.bilateralFilter(originalImage, 9, 300, 300)
    ReSized5 = cv2.resize(colorImage, (960, 540))

    # Masking edged image with our filtered color image
    cartoonImage = cv2.bitwise_and(colorImage, colorImage, mask=getEdge)
    ReSized6 = cv2.resize(cartoonImage, (960, 540))

    # Plotting the whole transition
    images = [ReSized1, ReSized2, ReSized3, ReSized4, ReSized5, ReSized6]
    titles = ["Original", "Grayscale", "Smoothened", "Edges", "Filtered", "Cartoon"]

    fig, axes = plt.subplots(3, 2, figsize=(8, 8),
                             subplot_kw={'xticks': [], 'yticks': []},
                             gridspec_kw=dict(hspace=0.2, wspace=0.1))

    for i, ax in enumerate(axes.flat):
        ax.imshow(images[i], cmap='gray')
        ax.set_title(titles[i])

    plt.show()

    # Save the cartoon image
    output_path = '/content/cartoon_image.jpg'
    cv2.imwrite(output_path, cv2.cvtColor(cartoonImage, cv2.COLOR_RGB2BGR))
    print(f"Cartoon image saved at: {output_path}")

upload('/content/AA.jpg')